[[redirects]]
  from = "/api/video-search"
  to = "https://snapshot.search.nicovideo.jp/api/v2/snapshot/video/contents/search?q=&targets=title&fields=contentId,title,viewCounter&_sort=-viewCounter&_offset=0&_limit=3&_context=apiguide"
  status = 200
  force = true

[build]
  functions = "netlify/functions"